//
//  DeveloperPreview.swift
//  AirbnbClone
//
//  Created by Pratik Haridas Ghadge on 28/09/25.
//

import Foundation

class DeveloperPreview {
	var listings: [Listing] = [
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "John Smith",
			ownerImageURL: "male-profile-photo",
			numberOfBedrooms: 4,
			numberOfBathrooms: 3,
			numberOfGuests: 4,
			numberOFBeds: 4,
			pricePerNight: 567,
			latitude: 25.7850,
			longitude: -80.1936,
			imageURLs: ["listing-1", "listing-4", "listing-7"],
			address: "124 Main St",
			city: "Miami",
			state: "Florida",
			title: "Miami Villa",
			rating: 4.86,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .pool, .balcony, .laundry, .tv],
			type: .villa
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "John Smith",
			ownerImageURL: "male-profile-photo",
			numberOfBedrooms: 4,
			numberOfBathrooms: 3,
			numberOfGuests: 4,
			numberOFBeds: 4,
			pricePerNight: 589,
			latitude: 25.7706,
			longitude: -80.1340,
			imageURLs: ["listing-2", "listing-5", "listing-9", "listing-1"],
			address: "250 Ocean Dr",
			city: "Miami",
			state: "Florida",
			title: "Miami Beach House",
			rating: 4.82,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .pool, .tv, .kitchen, .office],
			type: .house
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "Emma Watson",
			ownerImageURL: "female-profile-photo",
			numberOfBedrooms: 2,
			numberOfBathrooms: 2,
			numberOfGuests: 3,
			numberOFBeds: 2,
			pricePerNight: 312,
			latitude: 25.7617,
			longitude: -80.1918,
			imageURLs: ["listing-3", "listing-6", "listing-8"],
			address: "Downtown Brickell Ave",
			city: "Miami",
			state: "Florida",
			title: "Beautiful Miami apartment in downtown Brickell",
			rating: 4.32,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .tv, .balcony],
			type: .apartment
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "Harry Styles",
			ownerImageURL: "male-profile-photo",
			numberOfBedrooms: 5,
			numberOfBathrooms: 4,
			numberOfGuests: 6,
			numberOFBeds: 5,
			pricePerNight: 763,
			latitude: 34.2000,
			longitude: -118.0426,
			imageURLs: ["listing-4", "listing-2", "listing-10"],
			address: "456 Malibu Rd",
			city: "Los Angeles",
			state: "California",
			title: "Beautiful Los Angeles home in Malibu",
			rating: 4.97,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .office, .kitchen, .pool],
			type: .villa
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "Timothy Chalamet",
			ownerImageURL: "male-profile-photo",
			numberOfBedrooms: 3,
			numberOfBathrooms: 2,
			numberOfGuests: 4,
			numberOFBeds: 3,
			pricePerNight: 420,
			latitude: 34.1000,
			longitude: -118.1426,
			imageURLs: ["listing-5", "listing-7", "listing-3", "listing-9"],
			address: "789 Sunset Blvd",
			city: "Los Angeles",
			state: "California",
			title: "Cozy Hollywood Apartment",
			rating: 4.55,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .tv, .kitchen],
			type: .apartment
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "Olivia Brown",
			ownerImageURL: "female-profile-photo",
			numberOfBedrooms: 6,
			numberOfBathrooms: 5,
			numberOfGuests: 8,
			numberOFBeds: 6,
			pricePerNight: 980,
			latitude: 40.7128,
			longitude: -74.0060,
			imageURLs:  ["listing-6", "listing-1", "listing-8"],
			address: "12 Broadway St",
			city: "New York",
			state: "New York",
			title: "Luxury Manhattan Penthouse",
			rating: 4.95,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .balcony, .laundry, .office],
			type: .apartment
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "Liam Johnson",
			ownerImageURL: "male-profile-photo",
			numberOfBedrooms: 3,
			numberOfBathrooms: 2,
			numberOfGuests: 5,
			numberOFBeds: 3,
			pricePerNight: 340,
			latitude: 41.8781,
			longitude: -87.6298,
			imageURLs: ["listing-7", "listing-4", "listing-2", "listing-9"],
			address: "99 Lakeshore Dr",
			city: "Chicago",
			state: "Illinois",
			title: "Modern Chicago Condo",
			rating: 4.48,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .tv, .pool],
			type: .apartment
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "Sophia Davis",
			ownerImageURL: "female-profile-photo",
			numberOfBedrooms: 2,
			numberOfBathrooms: 1,
			numberOfGuests: 2,
			numberOFBeds: 2,
			pricePerNight: 210,
			latitude: 37.7749,
			longitude: -122.4194,
			imageURLs: ["listing-10", "listing-8", "listing-2", "listing-7"],
			address: "300 Market St",
			city: "San Francisco",
			state: "California",
			title: "Charming San Francisco Loft",
			rating: 4.22,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .kitchen],
			type: .apartment
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "David Wilson",
			ownerImageURL: "male-profile-photo",
			numberOfBedrooms: 4,
			numberOfBathrooms: 3,
			numberOfGuests: 5,
			numberOFBeds: 4,
			pricePerNight: 560,
			latitude: 47.6062,
			longitude: -122.3321,
			imageURLs: ["listing-8", "listing-10", "listing-5"],
			address: "500 Pine St",
			city: "Seattle",
			state: "Washington",
			title: "Spacious Seattle Family House",
			rating: 4.68,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .balcony, .tv, .laundry],
			type: .house
		),
		Listing(
			id: UUID().uuidString,
			ownerUserID: UUID().uuidString,
			ownerName: "Isabella Martinez",
			ownerImageURL: "female-profile-photo",
			numberOfBedrooms: 1,
			numberOfBathrooms: 1,
			numberOfGuests: 2,
			numberOFBeds: 1,
			pricePerNight: 150,
			latitude: 29.7604,
			longitude: -95.3698,
			imageURLs: ["listing-9", "listing-3", "listing-1", "listing-6"],
			address: "45 Main St",
			city: "Houston",
			state: "Texas",
			title: "Cozy Houston Studio",
			rating: 4.10,
			features: [.selfCheckin, .suprHost],
			amenities: [.wifi, .tv],
			type: .apartment
		)
	]


}
